spring:
  datasource:
    url: jdbc:h2:mem:securitydb
    driver-class-name: org.h2.Driver
    hikari:
      username: jonggae
      password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console