### 회원가입
POST localhost:8080/register
content-type: application/json

{
"username" : "CJW",
"password" : "1234",
"email" : "muvnelik@naver.com"
}

### 로그인
POST localhost:8080/login
content-type: application/json

{
  "username" : "CJW",
  "password" : "1234"
}

